export const pageMockedCmsResponse = [
  {
    metadata: { tags: [], concepts: [] },
    sys: {
      space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
      type: 'Entry',
      id: '2aJU4AF4YstDLW7VhiXgds',
      contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'appSection' } },
      revision: 1,
      createdAt: '2024-10-31T20:29:56.809Z',
      updatedAt: '2024-11-22T17:38:56.421Z',
      publishedAt: '2024-10-31T22:50:33.379Z',
      firstPublishedAt: '2024-10-31T22:50:33.379Z',
      publishedVersion: 4,
      environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
      locale: 'en-US',
    },
    fields: {
      id: '/',
      fields: [
        {
          metadata: { tags: [], concepts: [] },
          sys: {
            space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
            type: 'Entry',
            id: '66gV873xUQODXfBDYCYbih',
            contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'section' } },
            revision: 0,
            createdAt: '2024-11-05T20:46:41.986Z',
            updatedAt: '2024-11-22T17:18:25.204Z',
            environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
            locale: 'en-US',
          },
          fields: {
            name: 'Home page intro',
            type: 'sectionVertical',
            fields: [
              {
                metadata: { tags: [], concepts: [] },
                sys: {
                  space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
                  type: 'Entry',
                  id: '51OruIAIVJ903wRVdsSqCj',
                  contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'textBlock' } },
                  revision: 0,
                  createdAt: '2024-11-05T21:02:06.351Z',
                  updatedAt: '2024-11-17T22:19:31.481Z',
                  environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
                  locale: 'en-US',
                },
                fields: {
                  name: 'Intro',
                  text: {
                    data: {},
                    content: [
                      {
                        data: {},
                        content: [
                          { data: {}, marks: [], value: 'I build ', nodeType: 'text' },
                          { data: {}, marks: [{ type: 'bold' }], value: 'web applications', nodeType: 'text' },
                          {
                            data: {},
                            marks: [],
                            value: ' encompassing all stages of the process, with a strong focus on delivering ',
                            nodeType: 'text',
                          },
                          { data: {}, marks: [{ type: 'bold' }], value: 'high-quality', nodeType: 'text' },
                          { data: {}, marks: [], value: ', ', nodeType: 'text' },
                          { data: {}, marks: [{ type: 'bold' }], value: 'accessible', nodeType: 'text' },
                          { data: {}, marks: [], value: ', ', nodeType: 'text' },
                          { data: {}, marks: [{ type: 'bold' }], value: 'well-tested', nodeType: 'text' },
                          { data: {}, marks: [], value: ' and ', nodeType: 'text' },
                          { data: {}, marks: [{ type: 'bold' }], value: 'scalable', nodeType: 'text' },
                          { data: {}, marks: [], value: ' front-end solutions.', nodeType: 'text' },
                        ],
                        nodeType: 'paragraph',
                      },
                      {
                        data: {},
                        content: [
                          { data: {}, marks: [], value: 'Collaborate effectively within ', nodeType: 'text' },
                          { data: {}, marks: [{ type: 'bold' }], value: 'cross-functional teams', nodeType: 'text' },
                          { data: {}, marks: [], value: ', playing an active role in ', nodeType: 'text' },
                          { data: {}, marks: [{ type: 'bold' }], value: 'architectural discussions', nodeType: 'text' },
                          {
                            data: {},
                            marks: [],
                            value:
                              ' and contributing significantly to decision-making processes, fostering a unified and innovative approach.',
                            nodeType: 'text',
                          },
                        ],
                        nodeType: 'paragraph',
                      },
                      {
                        data: {},
                        content: [
                          { data: {}, marks: [], value: 'Take an active ', nodeType: 'text' },
                          { data: {}, marks: [{ type: 'bold' }], value: 'mentoring role', nodeType: 'text' },
                          {
                            data: {},
                            marks: [],
                            value: ' to support and empower junior team members, providing valuable code reviews and ',
                            nodeType: 'text',
                          },
                          { data: {}, marks: [{ type: 'bold' }], value: 'constructive feedback', nodeType: 'text' },
                          { data: {}, marks: [], value: '. Actively promote a culture of ', nodeType: 'text' },
                          { data: {}, marks: [{ type: 'bold' }], value: 'knowledge sharing', nodeType: 'text' },
                          { data: {}, marks: [], value: ', continuous ', nodeType: 'text' },
                          { data: {}, marks: [{ type: 'bold' }], value: 'learning', nodeType: 'text' },
                          { data: {}, marks: [], value: ', and ', nodeType: 'text' },
                          { data: {}, marks: [{ type: 'bold' }], value: 'collaboration', nodeType: 'text' },
                          { data: {}, marks: [], value: '.', nodeType: 'text' },
                        ],
                        nodeType: 'paragraph',
                      },
                    ],
                    nodeType: 'document',
                  },
                },
              },
            ],
          },
        },
        {
          metadata: { tags: [], concepts: [] },
          sys: {
            space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
            type: 'Entry',
            id: '4lthLkA8RpNqNuxp0WIQ4v',
            contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'section' } },
            revision: 0,
            createdAt: '2024-11-18T23:35:28.381Z',
            updatedAt: '2025-02-16T16:07:05.667Z',
            environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
            locale: 'en-US',
          },
          fields: {
            name: 'Experiences',
            title: 'Experiences',
            type: 'sectionVertical',
            fields: [
              {
                metadata: { tags: [], concepts: [] },
                sys: {
                  space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
                  type: 'Entry',
                  id: '5d62JkgkBzbDENfz3GlpDu',
                  contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'card' } },
                  revision: 0,
                  createdAt: '2024-11-22T17:25:42.598Z',
                  updatedAt: '2025-02-16T15:59:51.534Z',
                  environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
                  locale: 'en-US',
                },
                fields: {
                  name: 'ClearScore - Platform',
                  type: 'experience',
                  destinationUrl: '/clearscore-platform',
                  startDate: '2024-01-01',
                  title: 'ClearScore . Platform',
                  titleIcon: {
                    metadata: { tags: [], concepts: [] },
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
                      type: 'Asset',
                      id: 'mHShOCOG3YfIGWE7cHnKc',
                      revision: 0,
                      createdAt: '2024-11-13T19:30:45.555Z',
                      updatedAt: '2024-11-13T19:30:47.091Z',
                      environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
                      locale: 'en-US',
                    },
                    fields: {
                      title: 'arrow-outward',
                      file: {
                        url: '//images.ctfassets.net/sndcwofrh7cy/mHShOCOG3YfIGWE7cHnKc/90b90e614272a27b9125283f12597784/arrow-outward.svg',
                        details: { size: 192, image: { width: 24, height: 24 } },
                        fileName: 'arrow-outward.svg',
                        contentType: 'image/svg+xml',
                      },
                    },
                  },
                  subtitle: 'Frontend engineer',
                  description:
                    'Led front-end initiatives, developed a CMS-powered marketing website with SDUI, implemented automated A/B testing, optimised development workflows, improved knowledge sharing, mentored developers, and built a reusable SDUI form library.',
                  ctaAriaLabel: 'See more clearscore',
                },
              },
              {
                metadata: { tags: [], concepts: [] },
                sys: {
                  space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
                  type: 'Entry',
                  id: '7fXu0Iu916mOqfwOF1JmWw',
                  contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'card' } },
                  revision: 0,
                  createdAt: '2024-11-22T17:19:51.200Z',
                  updatedAt: '2025-02-16T16:00:12.772Z',
                  environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
                  locale: 'en-US',
                },
                fields: {
                  name: 'ClearScore - Drivescore',
                  type: 'experience',
                  destinationUrl: '/clearscore-drivescore',
                  startDate: '2020-01-06',
                  endDate: '2023-12-31',
                  title: 'ClearScore . Drivescore',
                  titleIcon: {
                    metadata: { tags: [], concepts: [] },
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
                      type: 'Asset',
                      id: 'mHShOCOG3YfIGWE7cHnKc',
                      revision: 0,
                      createdAt: '2024-11-13T19:30:45.555Z',
                      updatedAt: '2024-11-13T19:30:47.091Z',
                      environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
                      locale: 'en-US',
                    },
                    fields: {
                      title: 'arrow-outward',
                      file: {
                        url: '//images.ctfassets.net/sndcwofrh7cy/mHShOCOG3YfIGWE7cHnKc/90b90e614272a27b9125283f12597784/arrow-outward.svg',
                        details: { size: 192, image: { width: 24, height: 24 } },
                        fileName: 'arrow-outward.svg',
                        contentType: 'image/svg+xml',
                      },
                    },
                  },
                  subtitle: 'Frontend engineer',
                  description:
                    'Developed the frontend and everything JavaScript for a greenfield project "DriveScore," working within a hybrid approach that combined Agile, Extreme Programming (XP), Kanban, and Lean methodologies.',
                  ctaAriaLabel: 'See more drivescore',
                },
              },
            ],
            htmlRole: 'ul',
          },
        },
        {
          metadata: { tags: [], concepts: [] },
          sys: {
            space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
            type: 'Entry',
            id: '6f5lxMIHvPpITbHOIgth0n',
            contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'section' } },
            revision: 0,
            createdAt: '2024-11-22T17:38:51.107Z',
            updatedAt: '2025-02-16T16:57:31.476Z',
            environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
            locale: 'en-US',
          },
          fields: {
            name: 'Projects',
            title: 'Projects',
            type: 'sectionVertical',
            fields: [
              {
                metadata: { tags: [], concepts: [] },
                sys: {
                  space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
                  type: 'Entry',
                  id: '45Dqf9udHzQU4eEIrDhTVY',
                  contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'card' } },
                  revision: 0,
                  createdAt: '2024-11-22T17:39:05.579Z',
                  updatedAt: '2024-12-08T17:17:04.509Z',
                  environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
                  locale: 'en-US',
                },
                fields: {
                  name: 'Portfolio',
                  type: 'project',
                  destinationUrl: 'https://luigipalermo.com',
                  projectUrl: 'https://github.com/l-palermo/portfolio',
                  title: 'Portfolio',
                  ctaAriaLabel: 'See portfolio',  
                  titleIcon: {
                    metadata: { tags: [], concepts: [] },
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
                      type: 'Asset',
                      id: 'mHShOCOG3YfIGWE7cHnKc',
                      revision: 0,
                      createdAt: '2024-11-13T19:30:45.555Z',
                      updatedAt: '2024-11-13T19:30:47.091Z',
                      environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
                      locale: 'en-US',
                    },
                    fields: {
                      title: 'arrow-outward',
                      file: {
                        url: '//images.ctfassets.net/sndcwofrh7cy/mHShOCOG3YfIGWE7cHnKc/90b90e614272a27b9125283f12597784/arrow-outward.svg',
                        details: { size: 192, image: { width: 24, height: 24 } },
                        fileName: 'arrow-outward.svg',
                        contentType: 'image/svg+xml',
                      },
                    },
                  },
                  description:
                    "This website is built using Next.JS, React, and CSS Modules. It's an ongoing project, and more content and features will be added over time.",
                  fields: {
                    metadata: { tags: [], concepts: [] },
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
                      type: 'Entry',
                      id: '3nPhXnysR2AqwsdndfsZ5P',
                      contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'pillList' } },
                      revision: 0,
                      createdAt: '2024-11-22T18:44:05.201Z',
                      updatedAt: '2024-11-22T18:45:57.234Z',
                      environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
                      locale: 'en-US',
                    },
                    fields: {
                      name: 'Portfolio technologies',
                      technologies: ['React', 'Typescript', 'Next.js', 'CSS', 'Figma', 'Vercel'],
                    },
                  },
                  projectGithubLink: {
                    metadata: { tags: [], concepts: [] },
                    sys: {
                      space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
                      type: 'Entry',
                      id: '5zDhrFWGcIxgAVsqiUz1Zy',
                      contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'link' } },
                      revision: 0,
                      createdAt: '2024-11-22T23:21:21.711Z',
                      updatedAt: '2024-11-22T23:22:53.588Z',
                      environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
                      locale: 'en-US',
                    },
                    fields: {
                      name: 'Portfolio',
                      label: 'Portfolio github repo ',
                      url: 'https://github.com/l-palermo/portfolio',
                      icon: {
                        metadata: { tags: [], concepts: [] },
                        sys: {
                          space: { sys: { type: 'Link', linkType: 'Space', id: 'sndcwofrh7cy' } },
                          type: 'Asset',
                          id: '7CXS1rTIwWxDiHYS49lvqB',
                          revision: 0,
                          createdAt: '2024-11-13T19:30:44.566Z',
                          updatedAt: '2024-11-13T19:30:46.104Z',
                          environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
                          locale: 'en-US',
                        },
                        fields: {
                          title: 'github-logo',
                          file: {
                            url: '//images.ctfassets.net/sndcwofrh7cy/7CXS1rTIwWxDiHYS49lvqB/a8d4381cab481d14958e706f98cc8fc2/github-logo.svg',
                            details: { size: 576, image: { width: 24, height: 24 } },
                            fileName: 'github-logo.svg',
                            contentType: 'image/svg+xml',
                          },
                        },
                      },
                      iconOnly: true,
                      reverse: false,
                      isItemList: false,
                      opensInNewTab: true,
                    },
                  },
                },
              },
            ],
            htmlRole: 'ul',
          },
        },
      ],
    },
  },
];
